### ISSUE TITLE
[Bug]0.6.7 break on android 5.1.1 

### ISSUE THREAD

**Issue by iwater** [ammarahm-ed/react-native-mmkv-storage#196]
**Describe the bug**
works well on android 8.0 but break on android 5.1.1

**To Reproduce**
init a blank react native project
install react-native-mmkv-storage
start app

**Platform Information:**
 - OS: Android
 - React Native Version 0.66.4
 - Library Version 0.6.7

**Additional context**
FATAL EXCEPTION: create_react_context
Process: com.dde2021, PID: 8201
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/security/keystore/KeyGenParameterSpec$Builder;
	at androidx.security.crypto.MasterKeys.createAES256GCMKeyGenParameterSpec(MasterKeys.java:72)
	at androidx.security.crypto.MasterKeys.<clinit>(MasterKeys.java:55)
	at com.ammarahmed.mmkv.SecureKeystore.<init>(SecureKeystore.java:48)
	at com.ammarahmed.mmkv.RNMMKVModule.<init>(RNMMKVModule.java:52)
	at com.ammarahmed.mmkv.RNMMKVPackage.createNativeModules(RNMMKVPackage.java:17)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.security.keystore.KeyGenParameterSpec$Builder" on path: DexPathList[[zip file "/data/app/com.dde2021-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dde2021-1/lib/arm64, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 13 more
	Suppressed: java.lang.ClassNotFoundException: android.security.keystore.KeyGenParameterSpec$Builder
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 14 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

FATAL EXCEPTION: create_react_context
Process: com.dde2021, PID: 8201
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/security/keystore/KeyGenParameterSpec$Builder;
	at androidx.security.crypto.MasterKeys.createAES256GCMKeyGenParameterSpec(MasterKeys.java:72)
	at androidx.security.crypto.MasterKeys.<clinit>(MasterKeys.java:55)
	at com.ammarahmed.mmkv.SecureKeystore.<init>(SecureKeystore.java:48)
	at com.ammarahmed.mmkv.RNMMKVModule.<init>(RNMMKVModule.java:52)
	at com.ammarahmed.mmkv.RNMMKVPackage.createNativeModules(RNMMKVPackage.java:17)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.security.keystore.KeyGenParameterSpec$Builder" on path: DexPathList[[zip file "/data/app/com.dde2021-1/base.apk"],nativeLibraryDirectories=[/data/app/com.dde2021-1/lib/arm64, /vendor/lib64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 13 more
	Suppressed: java.lang.ClassNotFoundException: android.security.keystore.KeyGenParameterSpec$Builder
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 14 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by ammarahm-ed** [comment]
The library supports android 6.0 and above. API 23.

**Comment by ammarahm-ed** [comment]
Fixed in v0.6.8
